Add mobile navbar
alshakerM/my-instagram pull request #96
Opened 2022-01-13 17:44 UTC by alshakerM

Added a different NavBar for mobile users.
Changed margin from pixel to percentage for responsive reasons.

2022-01-13 21:11 UTC, alshakero reviewed
Wow, great work. I have some notes but I'm really toasted to review the code. I'll go through it tomorrow.

2022-01-14 19:41 UTC, alshakero requested changes
Great work. Left some notes.

2022-01-14 19:41 UTC, alshakero commented on components/Icons/MobileIcons.js
> +          stroke-Linecap="round"
```suggestion
          strokeLinecap="round"
```

2022-01-14 19:41 UTC, alshakero commented on components/NavBar/NavBar.module.css
> +  height: 44px;
I don't think you need to set the height. If you're not happy with how it looks, adjust paddings and margins.

```suggestion
```

2022-01-14 19:41 UTC, alshakero commented on components/NavBar/NavBar.module.css
> +  top: 96%;
Top 96% means the element height is 4%. Is it? 

You should do
```suggestion
  bottom: 0;
```

2022-01-15 22:00 UTC, alshakerM commented
Removed height and used padding 1px,
Edit on some code in  SVG to make it camelCase.
Remove 96% top and made it bottom 0

2022-01-16 14:29 UTC, alshakero approved these changes
LGTM. I'll merge this one because I need `useMediaQuery` in #100

2022-01-16 14:30 UTC, merged